title: "RedWine"
logo: "https://github.com/ainaramc/ainaramc.github.io/blob/main/logo.png?raw=true"
favicon: "https://raw.githubusercontent.com/ainaramc/ainaramc.github.io/refs/heads/main/favicon.ico"
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://ainaramc.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
